(* Pretty printers for the Rust AST *)
val pp_mutability : Format.formatter -> Rustc_ast.mutability -> unit
val pp_un_op : Format.formatter -> Rustc_ast.un_op -> unit
val pp_bin_op : Format.formatter -> Rustc_ast.bin_op -> unit
val pp_null_op : Format.formatter -> Rustc_ast.null_op -> unit
val pp_span : Format.formatter -> Rustc_ast.span -> unit
val pp_borrow_kind : Format.formatter -> Rustc_ast.borrow_kind -> unit
val pp_rkind : Format.formatter -> Rustc_ast.rkind -> unit
val pp_expr_kind : Format.formatter -> Rustc_ast.expr_kind -> unit
val pp_const_val : Format.formatter -> Rustc_ast.const_val -> unit
val pp_typ : Format.formatter -> Rustc_ast.typ -> unit
val pp_const : Format.formatter -> Rustc_ast.const -> unit
val pp_arg : Format.formatter -> Rustc_ast.arg -> unit
val pp_projection : Format.formatter -> Rustc_ast.projection -> unit
val pp_place : Format.formatter -> Rustc_ast.place -> unit
val pp_local_info : Format.formatter -> Rustc_ast.local_info -> unit
val pp_local_decl : Format.formatter -> Rustc_ast.local_decl -> unit
val pp_operand : Format.formatter -> Rustc_ast.operand -> unit
val pp_intrinsic : Format.formatter -> Rustc_ast.intrinsic -> unit
val pp_rvalue : Format.formatter -> Rustc_ast.rvalue -> unit
val pp_statment_kind : Format.formatter -> Rustc_ast.statement_kind -> unit
val pp_statement : Format.formatter -> Rustc_ast.statement -> unit
val pp_targets : Format.formatter -> Rustc_ast.targets -> unit
val pp_call_info : Format.formatter -> Rustc_ast.call_info -> unit
val pp_assert_message : Format.formatter -> Rustc_ast.assert_message -> unit
val pp_drop_info : Format.formatter -> Rustc_ast.drop_info -> unit
val pp_assert_info : Format.formatter -> Rustc_ast.assert_info -> unit
val pp_basic_block : Format.formatter -> Rustc_ast.basic_block -> unit
val pp_unwind_action : Format.formatter -> Rustc_ast.unwind_action -> unit
val pp_var_debug_info_content : Format.formatter -> Rustc_ast.var_debug_info_content -> unit
val pp_var_debug_info : Format.formatter -> Rustc_ast.var_debug_info -> unit
val pp_var_debug_info_fragment : Format.formatter -> Rustc_ast.var_debug_info_fragment -> unit
val pp_body : Format.formatter -> Rustc_ast.body -> unit